# Heroku Docker File
# pull official base image
FROM python:3.7-alpine

# set work directory
ADD . /should_i_buy_this_one
WORKDIR /should_i_buy_this_one

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBUG 0

# install psycopg2
RUN apk update \
	&& apk add gcc libc-dev make git libffi-dev openssl-dev python3-dev libxml2-dev libxslt-dev \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add postgresql-dev \
    && pip install psycopg2 \
    && apk del build-deps

# install dependencies
# COPY ./requirements.txt .
RUN pip install -r requirements.txt

RUN python ./manage.py makemigrations
RUN python ./manage.py migrate

# copy project
# COPY . .

# collect static files
RUN python manage.py collectstatic --noinput

# add and run as non-root user
# RUN adduser -D myuser
# USER myuser

# run gunicorn
CMD gunicorn should_i_buy_this_one.wsgi:application --bind 0.0.0.0:$PORT