FROM python:3.7-alpine

MAINTAINER Logan Davis 

EXPOSE 80

RUN apk add --no-cache gcc python3-dev musl-dev

ADD . /should_i_buy_this_one

WORKDIR /should_i_buy_this_one

RUN apk update && apk add gcc libc-dev make git libffi-dev openssl-dev python3-dev libxml2-dev libxslt-dev 

RUN pip install -r requirements.txt

RUN python ./manage.py makemigrations

RUN python ./manage.py migrate

CMD [ "python", "./manage.py", "runserver", "0.0.0.0:80" ]