# Generated by Django 3.0.5 on 2020-05-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='resultPercentile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
