# Generated by Django 3.0.5 on 2020-05-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_lookup_resultpercentile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookup',
            old_name='resultPercentile',
            new_name='resultValue',
        ),
    ]
