# Generated by Django 3.0.5 on 2020-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200502_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='priceWeight',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lookup',
            name='ratingWeight',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lookup',
            name='reviewCountWeight',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
